[package]
name = "anitag2vec"
version = "0.3.0-dev"
edition = "2024"
license = "MIT"
description = "Generate vector embeddings from Danbooru, Sakugabooru, Pixiv, MAL style tags."
authors = ["michael-0acf4 <root@afmichael.dev>"]
repository = "https://github.com/michael-0acf4/anitag2vec"
readme = "README.md"
keywords = ["ndarray", "onnx", "embeddings", "imageboard","tags"]
categories = ["science", "encoding"]
include = [
    "src/**/*.rs",
    "Cargo.toml",
    "LICENSE*",
    "README.md",
    # "build.rs"
]

[dependencies]
ahash = "0.8.12"
eyre = "0.6.12"
serde = "1.0.228"
serde_json = "1.0.149"
tokenizers = "0.22.2"
ndarray = "0.17.2"
itertools = "0.14.0"
reqwest = { version = "0.13.2", features = ["blocking"] }

# TODO:
# 0.23 once it lands
# tract-onnx = { git = "https://github.com/sonos/tract", rev = "43b3f0", package = "tract-onnx" }
tract-onnx = "0.23.3"
sha2 = "0.11.0"
hex = "0.4.3"
